ENT.Base 			= "npc_vj_aq_icky"
ENT.Type 			= "ai"
ENT.PrintName 		= "Aquatic Wild Life"
ENT.Author 			= "Cpt. Hazama"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "Aquatics"